### PR TITLE
recipes-appfw: Modify example node and python apps manifest

### PR DESCRIPTION
**Pull request by daweiwu**
```
1. Change the manifest of example node app can
   be parsed with python json module
2. Fix example python app fail to start issue
```

### CODE REVIEW

**Comment by daweiwu** [comment]
@klihub , please review.

**Comment by klihub** [comment]
Otherwise looks ok to me, but could you please change the host-side port for the python sample to something else than 2000-2004. Those could conflict with the port mappings for our other samples.

**Comment by daweiwu** [comment]
Thanks for review, updated.

**Comment by daweiwu** [comment]
CI fails due to AFT issue on Minnowboard.  @klihub , please help to merge . Thanks.

**Comment by klihub** [comment]
Looks good to me, I'll merge it.

**Pull request merged**
